apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-container
          image: abhishekf5/python-sample-app-demo:v1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: db-connection
              mountPath: /opt
          ports:
            - containerPort: 8000

      volumes:
        - name: db-connection
          configMap:
            name: test-cm
